### ISSUE TITLE
Create BTCC Exchange Adapter

### ISSUE THREAD

**Issue by gazbert** [gazbert/bxbot#12]
https://www.btcc.com/

API: 
* https://www.btcc.com/apidocs/usd-spot-exchange-market-data-rest-api
* https://www.btcc.com/apidocs/authentication-documentation

**Comment by gazbert** [comment]
Not done! ;-)

**Comment by jereanon** [comment]
BTCC is closed as of Oct 2nd -- may want to close this issue ;)

**Comment by gazbert** [comment]
Closed for Chinese trading, but still going for USD/BTC - https://exchange.btcc.com/

**Comment by gazbert** [comment]
Definitely closed now.
