### ISSUE TITLE
Update OKCoin Exchange Adapter to use v3 API

### ISSUE THREAD

**Issue by gazbert** [gazbert/bxbot#122]
The OKCoin V1 API is now deprecated and no longer works:
https://support.okcoin.com/hc/en-us/articles/360037694451-V1-API-Service-Deprecation-on-February-9-2020

The V3 API is documented here:
https://www.okcoin.com/docs/en/#spot-README

**Comment by razvv** [comment]
Hello gazbert - do you know the XChange java library? (https://github.com/knowm/XChange) 

"XChange is a library providing a simple and consistent API for interacting with a diverse set of crypto currency exchanges." (60+ exchanges)

I think that it might be useful rather than creating/updating the adapters by your own.

Regards,
razvv

**Comment by gazbert** [comment]
> Hello gazbert - do you know the XChange java library? (https://github.com/knowm/XChange)
> 
> "XChange is a library providing a simple and consistent API for interacting with a diverse set of crypto currency exchanges." (60+ exchanges)
> 
> I think that it might be useful rather than creating/updating the adapters by your own.
> 
> Regards,
> razvv

Hello razvv

Yes I know about XChange - it's a far more sophisticated project than this one!

There are no plans to switch to using XChange for the Trading API due to the amount of re-work involved - see https://github.com/gazbert/bxbot/issues/60#issuecomment-317260645

You're welcome to fork the bot and replace the Trading API + Exchange Adapter layer - it'll be a lot of work though :wink:

- gazbert

**Comment by razvv** [comment]
Hello gazbert,

Thank you for your explanation, now I understand. If I'll be using it the bot, I might contribute :)

razvv

**Comment by gazbert** [comment]
Closing issue as no takers.
