### ISSUE TITLE
KrakenChangeAdapter.java calculates nonce in incorrect format

### ISSUE THREAD

**Issue by roywasse** [gazbert/bxbot#127]
The KrakenAPI doesn't allow the nonce is currently formatted:
  nonce = System.currentTimeMillis() \ 1000;
Solution:
  nonce = System.currentTimeMillis();

**Comment by gazbert** [comment]
Thanks again for identifying another bug Roy. 

If you fancy having a go at a fix and PR, you're more than welcome :-)

I'm pretty busy at the moment with other stuff, but I plan on releasing a maintenance/dependency update release of the bot in the Spring.

- gazbert

**Comment by MarcDahlem** [comment]
When the bot is running a long time, I still receive errors from Kraken saying that the nonce is invalid.

According to this kraken article https://support.kraken.com/hc/en-us/articles/360022636092-Sample-implementations , the following implementation is an working example implementation for the rest api:


https://github.com/CryptoFacilities/REST-v3-Java/blob/master/Java/cfRestAPIv3/src/com/cryptofacilities/REST/v3/CfApiMethods.java#L104

Maybe, bxbot should use this calculation as well?

**Comment by roywasse** [comment]
Good point, the nonce is an abbreviation for number used once. If you run the bot long enough, the nonce will sometimes be created at the same time of the day and it won't be unique. Adding info from the date to the nonce make it unique again.
