### ISSUE TITLE
Wiki for documentation and discussions.

### ISSUE THREAD

**Issue by aCard0s0** [gazbert/bxbot#130]
I being exploring the codebase, it seems a solid project to invest my time. 
However I feel is very monolithic structure, files having 1000+ lines of code and too much log noice. 

I want to suggest an Github Wiki where we can not only document the proprieties of yaml configurations files, but also the architecture and patterns for a better performance, maintenance and scalability.

I open to contribute in some new feature and rework on the old one if needed.
Congratulation for the work so far.

Regards,
André Cardoso

**Comment by gazbert** [comment]
Thanks for the feedback and the offer to get involved with the project @aCard0s0 

Yes, the project has grown pretty big and could do with a refresh! I'm really busy with other stuff at the moment and just keeping the lights on with maintenance updates to be honest. It would be great to see others get involved and evolve the bot from a hobby project I created 6+ years ago to something more professional :-)

It might be worth taking a look at Tim Molter's excellent [Xchange](https://github.com/knowm/XChange]) project for crypto exchange adapters/trading APIs - it's much more advanced (tech wise + functionality) than BX-bot and might be of interest...

Good idea with the Wiki - I've just not had time to create/maintain one and have dumped everything in the README. I'll create an empty Wiki - feel free to edit!

**Comment by gazbert** [comment]
Closing - no updates for 1+ years.
