### ISSUE TITLE
Improved Test-Adapters

### ISSUE THREAD

**Issue by MarcDahlem** [gazbert/bxbot#137]
**Describe the solution you'd like**
I would like to have a better test exchange adapter, which:
* keeps track of running orders
* can run real-time with every possible exchange ("try-mode")

**Describe alternatives you've considered**
* it would be nice to use stored ticker data instead of running real time to backtest strategies.

**Additional context**
For the main feature, I created a (currently red/wrong code-formatted) PR: https://github.com/gazbert/bxbot/pull/136
Also for the alternative way, I added an example "backtest" adapter in https://github.com/gazbert/bxbot/pull/135
(This backtest adapter adds also ta4j examples for strategies).

Before I work further on those PRs (Tests, Formatting etc), I would like to discuss about the general idea.
@gazbert can you please check the ideas of the PRs? Thx a lot!

**Comment by MarcDahlem** [comment]
Great! Of course its fine for me if it takes a bit longer to merge and release.
In the meanwhile, I created a bunch of strategies, helpers and so on in my fork.
So I dont need the release for me :-)

As I know that you are interested in the PRs in general, I will finish the open PRs and will open a few more for other enhancements ;-)

Btw: I realized that it is really hard to share code/utils between the exchanges and the strategies (for example BreakEven-Calculations), between the core and the strategies (E-Mail sending e.g. on Buy and Sell events) or between the core and the exchanges (Inject classes and beans). Do you have a preference, where to put some utils or shared code? The *api modules would work, but it feels like the wrong place to put shared code in an interface module)

**Comment by gazbert** [comment]
Merged #136  to master.

TODO:

- [ ] Fix Checkstyle issues.
- [ ] Update/enhance Javadoc for new TryModeExchangeAdapter.
- [ ] Add test for new TryModeExchangeAdapter... I know... sorry, ;-)
- [ ] Update/enhance comments for config/exchange.yml
- [ ] Update README to tell folks about the new and improved Test/Simulation exchange adapter functionality :-)

**Comment by gazbert** [comment]
Ready to go...

**Comment by gazbert** [comment]
Released.
