### ISSUE TITLE
build process has ~ 2 tests that fail

### ISSUE THREAD

**Issue by datasmithtech** [gazbert/bxbot#48]
i ran the build , and i noticed a couple of tests failed
bxbot-xml-datastore:test

Tests
com.gazbert.bxbot.datastore.config.engine  3 1 0 0.660s 66% 
com.gazbert.bxbot.datastore.config.exchange   

Class
com.gazbert.bxbot.datastore.config.engine.TestEngineConfigurationManagement  3 1 0 0.660s 66% 
com.gazbert.bxbot.datastore.config.exchange.TestExchangeConfigurationManagement   

i am running on windows using latest stable release

**Comment by gazbert** [comment]
Hi Larry thanks for letting me know. I mostly develop on linux/osx, so
could be an OS thing - will take a look on my work Windows machine on
Monday. Guess you can @ignore the tests to get a build in the meantime.

Will keep you posted.

-- sent from my phone --

**Comment by gazbert** [comment]
Added fix to close config loading/saving input/output streams. The bot was getting away with this on Linux/OSX, but running the xml-datastore unit tests on Windows highlighted the issue - thanks to @datasmithtech for spotting this.
