### ISSUE TITLE
Create bitFlyer Exchange Adapter

### ISSUE THREAD

**Issue by gazbert** [gazbert/bxbot#53]
https://bitflyer.jp/

API:
https://lightning.bitflyer.jp/docs?lang=en

**Comment by jereanon** [comment]
It's not really clear if they have any sort of testing environment for their api? 

https://lightning.bitflyer.jp/docs/playground . -- this says it is a live environment! eeep!

**Comment by gazbert** [comment]
Closing - no updates for 1+ years.
