### ISSUE TITLE
Filter getYourOpenOrders by Market

### ISSUE THREAD

**Issue by askosyrskiy** [gazbert/bxbot#55]
Hi @gazbert,

I found an issue with Gemini adapter. When you working with 2 markets, for example BTCUSD and ETHUSD same time getYourOpenOrders function returns all your open orders regardless marketId parameter for the function. Not sure if was designed this way or  its an issue.

I have added this fix to support multiple markets:

![image](https://user-images.githubusercontent.com/14056133/27296403-b428fef2-54ee-11e7-9613-5c4183676531.png)

**Comment by gazbert** [comment]
Hi Alexey 

This is definitely a bug. All the adapters were based off the original BTC-e adapter, which does filter on market id. But Gemini, Bitfinex, Bitstamp, GDAX, and ItBit do not - no idea how I missed this. I only trade on 1 market on these exchanges, so didn't spot the bug. Great find!

Do you want to submit a PR? Your fix snippet is the way to go... I can get the fix in pretty quick for all the adapters, but just wanted to check in case you wanted to contribute any code, or are happy for me sort it out?

Cheers
Gareth

**Comment by askosyrskiy** [comment]
Will be happy for you to fix it :) I have limited time now for the PR and testing it.

Thank you

**Comment by gazbert** [comment]
Sure thing. Should be straightforward for Gemini, Bitfinex, GDAX, and ItBit - the open order response contains the market id.

Bitstamp is a bit more work - I'll  need to update to v2 of the exchange API in order to distinguish between the markets... Muh. ;-)

**Comment by gazbert** [comment]
Released.
