### ISSUE TITLE
Using EmailAlerter in strategies

### ISSUE THREAD

**Issue by askosyrskiy** [gazbert/bxbot#56]
Hi Gareth,

I am not so familiar with Spring, but is there any way to use EmailAlerter on strategies? For example, I would like to notify myself about order executions.

**Comment by gazbert** [comment]
Not at the moment. The EmailAlerter is an internal component and was designed to be used by the core engine to notify users about bot crashes.

It's fairly easy to create your own EmailAlerter and bundle it with your strategies - I think some folks already do this as well as record their trades/orders in an external database. 

To change to the bot to make the EmailAlerter available would require a fair bit of work. One approach might be to create an EmailAlertService in a new bxbot-strategy-services module/jar. Strats would be dependent on this if they wanted to send email alerts. The new module could re-use the existing repository layers etc... Sadly, I've not got time to do this at the moment as the day job is pretty hectic (!) and most of my free time is spent working on a Blockchain project, but feel free to fork the repo and have a go!

**Comment by askosyrskiy** [comment]
Thank you @gazbert I will try to do something as you suggested.
