### ISSUE TITLE
Create proxy server for routing BX-bot UI admin commands to BX-bots in the cloud

### ISSUE THREAD

**Issue by gazbert** [gazbert/bxbot#58]
Build a simple proxy server for routing commands from BX-bot UI to BX-bots running in the cloud:
https://github.com/gazbert/bxbot-ui-server

This new app will consume a bot's REST API - #32 

BX-bot UI Server will provide a REST API for user agents to consume in order to manage multiple bots:
* BX-bot UI - https://github.com/gazbert/bxbot-ui
* Android app
* iOS app

**Comment by gazbert** [comment]
On-hold.
Focusing on building a React UI (#101) for managing a single bot first.

**Comment by Bisconcini** [comment]
Sorry. Why the creation of a proxy server for routing from UI to CORE (bx-bot)? Can't UI consume CORE directly? If the ideia is a reverse proxy, your GUI server can't route to COREs by yourself?

**Comment by gazbert** [comment]
Closing. UI will attach to 1 instance of BX-bot. KISS and all that...
