### ISSUE TITLE
Create Android app for administering BX-bot

### ISSUE THREAD

**Issue by gazbert** [gazbert/bxbot#6]
Create iOS app for administering the bot.

iOS devices will use the REST API provided by bxbot-ui-server:
https://github.com/gazbert/bxbot-ui-server

This work will be done in a new GitHub project.

**Comment by tmadhavan** [comment]
I may be able to have a look at this at some point, unless you've already got Boy on the case.

**Comment by gazbert** [comment]
Get stuck in! I've only been tinkering until now.

I'm hacking at the REST API at the mo - still early days, but the endpoints for configuring the bot are starting to firm up. 

I guess you could start knocking out the base 'droid app for now and wire up the REST API when I get my backside into gear ;-)

**Comment by tmadhavan** [comment]
Alright cool, well I'm hopping off to Australia for a bit anyway, so perhaps when I get back :-D

**Comment by gazbert** [comment]
Android devices will use the REST API provided by bxbot-ui-server:
https://github.com/gazbert/bxbot-ui-server

**Comment by dudhatparesh** [comment]
Hi I can help for Android.
Let me know if this is still open.

**Comment by gazbert** [comment]
Hi @dudhatparesh - thanks for the offer, yes this is still open, go for it! 

The REST API that the devices/Web UI will consume is not stable yet - #58 - I'm still evolving the design etc... but authentication will be done using JWT/TLS and I'd say the REST API defined in https://github.com/gazbert/bxbot-ui-server is about 80% there...

If we could get an android app working (even without JWT/TLS) to the same level of functionality as https://github.com/gazbert/bxbot-ui, that would be awesome!

There is a placeholder project already setup - https://github.com/gazbert/bxbot-android - feel free to fork this.

No rush for any of this, just code away whenever you get a chance... ;-)

My priorities are to add a Settings screen to https://github.com/gazbert/bxbot-ui to configure multiple bots, and then get it working e2e with https://github.com/gazbert/bxbot-ui-server  and https://github.com/gazbert/bxbot using JWT/TLS - the Runtime screen to stop/start/view logs will come later.

I'll assign the ticket to you.

**Comment by gazbert** [comment]
Closing. No progress been made.
Will build React Native app instead - #102
