### ISSUE TITLE
Integrating with XChange?

### ISSUE THREAD

**Issue by mugenZebra** [gazbert/bxbot#60]
[XChange](https://github.com/timmolter/XChange) is a Java library for a standardized API interface to 50+ exchanges. I think it can be wonderful to integrate with this project. Any thought?

**Comment by gazbert** [comment]
Hi there

There's currently no plans to integrate with XChange...

Tim Molter's project is a _lot_ more advanced and provides a much richer API for Exchange integration than BX-bot. The Trading API used by BX-bot contains the bare-bones operations to allow basic limit order trading. BX-bot is a mere hobby project in comparison!

The current plan for me is to get the Admin UI up and running so folks can manage their bots remotely. But feel free to fork the project and have a go! I guess you could create an Exchange Adapter for XChange, and only adapt the operations on the existing Trading API... 

Or you could be really brave, and replace the Exchange Adapter framework completely... and use XChange directly from your Trading Strategies!
