### ISSUE TITLE
Adapter for Cex.io

### ISSUE THREAD

**Issue by gayanW** [gazbert/bxbot#69]
I'm no expert on this. However If this is not urgent, I'd like to write a adapter for this in my free time.

**Comment by gazbert** [comment]
Hi Gayan, go for it!
No rush for anything, if you need any help, then give me a shout.
G

**Comment by gazbert** [comment]
Closing - no updates for 1+ years.

**Comment by gazbert** [comment]
Closing - no updates for 1+ years.
