### ISSUE TITLE
Bug at GdaxExchangeAdapter

### ISSUE THREAD

**Issue by kuceraf** [gazbert/bxbot#73]
When creating params for new order request 
`params.put("price", new DecimalFormat("#.##").format(price));`
Comma is used as decimal number separator at my enviroment. 
Gdax requires dot as decimal number separator, thus the request fails.

**Comment by gazbert** [comment]
Hi @kuceraf  - thanks for spotting this. Which environment do you run in btw?

This issue will affect all the exchange adapters, so I'll bring in your PR and push it up into the AbstractExchangeAdapter base class.

The sample Trading Strat will also be affected too - I'll raise a separate ticket for this.

**Comment by kuceraf** [comment]
Hi @gazbert, yes it's right, I've examined just the gdax adapter. 
I run it on Windows 10, with Czech localization (and the localization probably cause the problem)

**Comment by gazbert** [comment]
Cool. I should get some time tomorrow night after work to sort out the other adapters & trading strat out.

**Comment by gazbert** [comment]
Looks like the ExampleScalpingStrategy is ok - it only uses the DecimalFormat in the log statements.

**Comment by gazbert** [comment]
Will try and get a 0.8.4 release out tomorrow night.

**Comment by gazbert** [comment]
Released.
