### ISSUE TITLE
introduce OHLC over time period

### ISSUE THREAD

**Issue by jereanon** [gazbert/bxbot#75]
I'm interested in adding support for Open High Low Close "bars" over a specific time period.

e.g., https://www.investopedia.com/terms/o/ohlcchart.asp

I'd like to do this as the first step in adding a concept of indicators (e.g., EMA) so that we can support more complex trading strategies.

**Comment by gazbert** [comment]
Go for it! GDAX seems to support historic stats - https://docs.gdax.com/#get-historic-rates. Not checked the other exchanges, but if they don't you could Javadoc they don't and throw UnsupportedOperationException in the new Trading API operations.

**Comment by gazbert** [comment]
A basic Ticker is going in as part of #81 - might be useful.

**Comment by gazbert** [comment]
Closing. No progress made. Can be resurrected if needed :-)
