### ISSUE TITLE
Debugging bx-bot

### ISSUE THREAD

**Issue by jurepetrovic** [gazbert/bxbot#88]
Hello Gents, 

how would you go about debugging bx-bot in eclipse? 
I cannot seem to get a working debug configuration together...

Rgds ,
Jure

**Comment by gazbert** [comment]
Hi @jurepetrovic, you might get some help from: https://gitter.im/BX-bot/Lobby

I use IntelliJ, but STS/Eclipse should work the same way: BXBot.java is the main class, set the working directory, and that should be it: : https://imgur.com/a/0CWPD

HTH

**Comment by jurepetrovic** [comment]
Thanks. I already managed debugging in the meantime.
Springboot made it a bit harder. 

If I get that correctly you're using springboot only because of the built-in webserver?

**Comment by gazbert** [comment]
Yes, Boot is being used to support the REST API to configure and manage the bot remotely as per #32 - currently WIP.
