### ISSUE TITLE
How to see the bot work?

### ISSUE THREAD

**Issue by Plyshu** [gazbert/bxbot#91]
I apologize in advance for translate google.
I installed the bot and launched it, but I can not understand where you can see his work. I opened a lot of information but very much to understand something. I apologize for such a stupid question

**Comment by gazbert** [comment]
You can tail the log file when the bot is running outside of the IDE too - https://github.com/gazbert/bxbot#logging - it sticks out useful log messages (e.g. order management) at info level.
