### ISSUE TITLE
Backtesting

### ISSUE THREAD

**Issue by Gabri** [gazbert/bxbot#94]
Hello, really interesting project (I'll try it soon).
Reading the documentation I haven't found anything regarding backtesting, I think it's a fundamental feature to test strategies with past data. I think it should be considered in the roadmap.

Is there the chance to make paper trading? For gdax, for example, we just need to use their sandbox?

Thanks

**Comment by gazbert** [comment]
Closing. No progress made. Can be resurrected if needed :-)
